
mysql:
  host: 192.168.102.138
  port: 8066

spring:
  datasource:
    druid:
      name: default
#      url: jdbc:mysql://${mysql.host}:${mysql.port}?connectionAttributes=tenant:dhl&useAffectedRows=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://${mysql.host}:${mysql.port}/cml?&useAffectedRows=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081